FROM node:24-alpine3.23 as builder
WORKDIR /app 
COPY package*.json ./
RUN npm install 
COPY . . 
RUN npm run build

FROM node:24-alpine3.23 as runner 
WORKDIR /app 
COPY --from=builder /app/dist ./dist 
COPY --from=builder /app/package*.json ./ 
COPY --from=builder /app/config ./config
RUN npm install --omit=dev 
USER node 
EXPOSE 8081
CMD ["node","dist/main.js"]